### ISSUE TITLE
Add a possibility to navigate to external web links 

### ISSUE THREAD

**Issue by antmanin** [JordiFerrerB/sistel_menu_extension#1]
Hello! Could you please tell if you're going to add "Open external URL" feature?

**Comment by JordiFerrerB** [comment]
> Hello! Could you please tell if you're going to add "Open external URL" feature?

Hi @antmanin! To add external urls to the menu would be great. It´s on my "To Do" list for today. Expect it to be launched early next week. Thank you very much.

**Comment by antmanin** [comment]
@JordiFerrerB thank you!
